### ISSUE TITLE
Perserve queue after restart

### ISSUE THREAD

**Issue by qixils** [HTSTEM/MusicBot#10]
Would be useful if a critical issue is found (or we just want to patch something) and we don't want to clear a queue that break the 2k char limit

**Comment by adamthedog** [comment]
Isn't Botter already running a SQL server? If so, we can easily save a list of song URLs to act as the queue and just pop the top song when it needs to play.

**Comment by Bottersnike** [comment]
I'm not running an SQL server, but a lot of the bots have an sqlite file. I can probably implement one in a few days.

**Comment by hanss314** [comment]
This is implemented now.
