### ISSUE TITLE
Better queue system..?

### ISSUE THREAD

**Issue by qixils** [HTSTEM/MusicBot#11]
The current queue system is perfectly fine... if we let people queue only one song at a time. However, I realized I don't like this approach very much after I used services like [Dubtrack](https://dubtrack.com), and checked out [jagrosh's musicbot](https://github.com/jagrosh/musicbot). Both essentially let you have your own personal queue (maybe even your own personal auto playlist? that's a separate request entirely tho) which you can add songs to at any time. One will then get sent into the bot's song queue, and once the song is played, the next song is added. This is done until the user's personal queue is empty, or they run a command to pause their personal queue (which would also remove their current song from the global queue).

If this is implemented, personal user queues shouldn't be cleared when disconnecting from a voice channel or when the bot restarts. This would obviously depend on #10 but I don't see that being a big issue as that sounds like a much easier and higher priority task to accomplish...

**Comment by qixils** [comment]
This might be something I try to work on for Hacktoberfest... we'll see :eyes:

**Comment by adamthedog** [comment]
Kinda like I suggested in #10, we can use a SQL server to attach a list of song URLs to a user-id and pop whichever when necessary.

**Comment by hanss314** [comment]
By personal user queues do you mean just playing something out of the likes?

**Comment by qixils** [comment]
I mean a... literal personal user queue?
- User001: !queue song.url
- Bot: Added song to your personal queue.
- Bot: User001's `song` is now playing!
- User001: !queue song2
- User001: !queue song3
- Bot: Added songs to your personal queue.
- User002: !queue SONG
- Bot: Song added to personal queue.
- [User001's `song` finishes]
- Bot: User002's `SONG` is now playing!
- [Song Finish]
- Bot: User001's `song2` is now playing!
- Bot: User001's `song3` is now playing!

I don't know how else to describe it besides using an example... hopefully that helps

**Comment by hanss314** [comment]
Ah, okay. This is definitely out of the scope of the original project and is moving into feature creep territory. I don't want to implement or maintain this.

**Comment by hanss314** [comment]
Okay, this actually isn't that bad

**Comment by hanss314** [comment]
Implemented in fee5c954d695961c30662f8722b821224a8ee6cb and 4518149d42c6e9921604967b49544a93233980c2
