### ISSUE TITLE
Fix the folder directories

### ISSUE THREAD

**Issue by hanss314** [HTSTEM/MusicBot#12]
bot.py should be in the same folder run.sh is running from. The current setup creates a pain of file directories and everything. Pycharm debugger doesn't work on .sh scripts and if I try debugging by running bot.py there's a lot of file not founds. It's also just a pain to work with in general.

**Comment by Bottersnike** [comment]
Are you unable to point pycharm at `musicbot/bot.py`? The start scripts are currently positioned in such a way that the code and internals are hidden for the person using it and the deeper into the tree you go the less likely you are to need to view those files unless you're a dev. (Hide all the pys but make the start up scripts and the config easily accessible)

**Comment by hanss314** [comment]
It's still just a pain to work with if you're running from command line without a bash loop. Is there any good reason the structure is this way?

**Comment by Bottersnike** [comment]
Yes. It is designed to look elegant. From the exterior view of the tree, there are no source files visible, only start scripts. This is designed to make it look appealing from a user-looking-at-repo point of view. The trace-off from a developer's point of view is adding `musicbot/` to the start of any system calls from a terminal which is a minor price to pay for the ability to have a nice clean repo with clear scripts. The alternative is to move `config/` to `musicbot/config/` but then we start to obscure the location of config files.

**Comment by hanss314** [comment]
Fine
