### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by Bottersnike** [HTSTEM/MusicBot#27]
At current, HTTP will 502 instead of redirect. I don't have access to the server currently but will setup an nginx rule for it soon.

(For ref: https://bjornjohansen.no/redirect-to-https-with-nginx)

**Comment by hanss314** [comment]
This isn't a Musicbot issue, and you don't have perms to the nginx config.

**Comment by hanss314** [comment]
Done
