### ISSUE TITLE
How do we do the perms?

### ISSUE THREAD

**Issue by hanss314** [HTSTEM/MusicBot#5]
As things stand, the current perm system is not good enough. I also don't like the rhino permission system because it's tedious to type out every single command you want to have permissions set up for. Any ideas? I'm thinking of different groups of commands based on how dangerous or similar they are, then we could just setup a config file for those.

**Comment by Bottersnike** [comment]
All of the commands already have categories applied to them? We could set perms per-category and use that?

**Comment by hanss314** [comment]
seems good

**Comment by hanss314** [comment]
working on it
