### ISSUE TITLE
What is this line here for? the search command is not a valid answer

### ISSUE THREAD

**Issue by hanss314** [HTSTEM/MusicBot#7]
https://github.com/HTSTEM/MusicBot/blob/05cf7298304067512878f690950a5a93124fe11c/musicbot/cogs/music.py#L246

**Comment by Bottersnike** [comment]
First off, I believe you wrote that line. Secondly, it appears to check is the message is a command and this if you don't do y or n and instead go to run another command it's cool with that.

**Comment by hanss314** [comment]
oh wait, it was code copied from rhinomusicbot
